### ISSUE TITLE
OSL texture3d() calls for field3d require tests

### ISSUE THREAD

**Issue by luisbarrancos** [appleseedhq/appleseed-maya#100]

**Comment by luisbarrancos** [comment]
So far, field3d files seem to work fine, but accessing individual channels via subimage strings doesn't seem to work. Maya fluids can be baked to f3d files via https://github.com/magic-box/Field3DMayaPlugin

**Comment by luisbarrancos** [comment]
The string access to the channel is via <namespace>::<node name>:<shape name>:<channel name>
I.e, without a namespace, Flame:flameShape:temperature, Flame:flameShape:density.

**Comment by dictoon** [comment]
What's the status of this ticket? Are `texture3d()` calls working as expected? Are more tests required? Is there development work to be done?

**Comment by luisbarrancos** [comment]
Tests are done, and we can read and access sub-images/channels in *.f3d files. We can convert Maya Fluids caches into f3d files with the Maya and F3d API, so the work is extending the fluids with an appleseed section to convert the caches to F3d and an exporter that provides the channel name convention (namespace & node/shape based) to the fluids channels. The result would be passed to the volumetric closures. Perhaps it's best to close this and file a new ticket for the cache to f3d conversion.
