### ISSUE TITLE
Reimplement common globals tab

### ISSUE THREAD

**Issue by est77** [appleseedhq/appleseed-maya#105]
We try to reuse the Maya common globals at the moment, doing some hacks to modify the image formats menu. It's kind of ugly and also buggy.

We should reimplement it, adding only the controls that make sense for appleseed and without hacks.

**Comment by luisbarrancos** [comment]
With OIIO supported formats, this changed a bit
https://github.com/appleseedhq/appleseed/issues/2411
https://github.com/appleseedhq/appleseed/pull/2445

**Comment by Mango-3** [comment]
Seems fixed with commit e7052900dcc636bea232c8bf2944c7dd349fb884
I think this issue can be closed.
