### ISSUE TITLE
Add URL to link to appleseed-maya node documentation

### ISSUE THREAD

**Issue by luisbarrancos** [appleseedhq/appleseed-maya#150]
Right now, Gaffer, Max recognize the URL metadata token for the help system, linking to the appleseed-maya RTD docs, but Maya is missing this functionality.

**Comment by dictoon** [comment]
@luisbarrancos You moved this to the Done column but havent't closed it. Is it done?

**Comment by luisbarrancos** [comment]
@dictoon you're right, i moved to WIP again. It's not done yet, requires some changes to the AEtemplates in Maya.

**Comment by luisbarrancos** [comment]
Done in https://github.com/appleseedhq/appleseed-maya/pull/168
