### ISSUE TITLE
Optionally disable export of smooth normals and tangents

### ISSUE THREAD

**Issue by est77** [appleseedhq/appleseed-maya#20]
Add some attributes to control mesh export.
Now, smooth normals are exported always and smooth tangents are exported if uvs are present.

**Comment by luisbarrancos** [comment]
@est77 even if we set normals to face normals explicitly in Maya/UV ?

**Comment by est77** [comment]
I want to add some checkboxes to let the user disable exporting of normals and specially tangents.
Right now we export everything. Should be easy.

**Comment by est77** [comment]
Done in 57b707dfbb2a66d00675c9dc0e30f04aea3ad748
