### ISSUE TITLE
Missing EXR and PNG entries after loading a scene

### ISSUE THREAD

**Issue by luisbarrancos** [appleseedhq/appleseed-maya#205]
Creating a new scene, loading the plugin, shows the image format menu updated with the formats supported by appleseed: EXR and PNG.
Loading a previously saved scene, shows the default Maya menu, with all its options, and missing the entry for EXR (whilst PNG has the Maya default PNG - *defaultRenderGlobals.imageFormat 7*).
This effectively makes it impossible to batch render loaded scenes as EXR.
Steps to reproduce:

1. load plugin
2. open previously saved scene (if EXR and PNG appear, proceed to 3)
3. open another previously saved scene, the full Maya image format menu would now appear

**Comment by Mango-3** [comment]
This is related to issue #105
The reuse of Maya's `Common` render settings tab is not very robust.  

I can reproduce this also when I start with an empty scene (with Arnold as default render engine set) and then switch to appleseed.

**Comment by luisbarrancos** [comment]
@Mango-3 thanks for the heads up

**Comment by est77** [comment]
I have seen this a few times.
Some renderers reuse the Maya common tab. The good points are that users are familiar with it and that settings are preserved if you change renderers. It's quite likely that the way we update the format menu it is not correct. I'd check that before going into all the work to recreate Maya's common tab.

**Comment by luisbarrancos** [comment]
@est77 thanks. Since this is related to #105 i'll be closing this.
Also, since we support the formats supported by OIIO, see https://github.com/appleseedhq/appleseed/issues/2411 and https://github.com/appleseedhq/appleseed/pull/2445 the scope of #105 might've been expanded.
