### ISSUE TITLE
Terminator attributes not classified correctly, ungrouped

### ISSUE THREAD

**Issue by luisbarrancos** [appleseedhq/appleseed-maya#228]
Pull request https://github.com/appleseedhq/appleseed-maya/pull/224 introduced a bug
see screenshot:

![shot](https://user-images.githubusercontent.com/387352/70587608-597d0080-1c05-11ea-8879-964f2aa1d1f1.png)

presently the terminator attributes are mingling with the Arnold attributes, but they should be in the *appleseed* section, ideally under *rendering* sub-section.

**Comment by Mango-3** [comment]
Ray Bias functionality was removed from appleseed and appleseed-Maya code. I don't see them on my System and I did not add them with the shadow terminator PR. I guess @luisbarrancos you have a left-over Python script where it was still exposed. 

here on my system:
![Capture](https://user-images.githubusercontent.com/22252558/70649888-b3f27d00-1c56-11ea-9197-3a0d2e63844f.PNG)

**Comment by dictoon** [comment]
@luisbarrancos Please confirm @Mango-3's hypothesis. Closing this ticket for now, please reopen if the problem remains.
