### ISSUE TITLE
Physical sky does not work

### ISSUE THREAD

**Issue by dictoon** [appleseedhq/appleseed-maya#30]
In the script editor:

    # Error: line 0: KeyError: file D:\dev\appleseed-maya\module\scripts\mtap_initialize.py line 145: pskSunAzi

**Comment by haggi** [comment]
I'm working on it now. The issue above is sovled. But I have some other questions:
The first image shows an preetham physical sky with an almost horizontal sun:
![preetham1](https://cloud.githubusercontent.com/assets/1830366/13547948/07fa0ae0-e2e4-11e5-8bbc-cdadc400a77b.jpg)
The secon one a preetham with a sun almost from above:
![preetham2](https://cloud.githubusercontent.com/assets/1830366/13547949/0bbaf43c-e2e4-11e5-9999-edfa2834d52d.jpg)
I'm getting two highlights a sharp sun and a quite diffuse one. Is this a feature of physical sky?
And I'd expect to get a greater difference in the sky colors if the sun angle changes from vertical to horizontal.

**Comment by haggi** [comment]
Here you can see a nice shadow without an extra sun light.

![shadow](https://cloud.githubusercontent.com/assets/1830366/13555362/07a7808c-e3bf-11e5-83e8-c253efc574bb.jpg)

**Comment by dictoon** [comment]
How do you render the dome?

**Comment by dictoon** [comment]
For reference, here are two images from the test suite, both using the Preetham physical sky model (no sun):

Sun at 0°:
![image](https://cloud.githubusercontent.com/assets/321290/13609599/eee45844-e559-11e5-89f0-dbd7b65ef63f.png)

Sun at 86°:
![image](https://cloud.githubusercontent.com/assets/321290/13609613/007d2306-e55a-11e5-82dd-0270049ef910.png)

**Comment by haggi** [comment]
Arrgh.... I just had a look at the exported appleseed file and it seems that I export a directional light, but not a sunLight. I'll fix that.

**Comment by dictoon** [comment]
The physical sun light is just a directional light with a particular spectrum, I don't think this is related to the problem at hands.

**Comment by dictoon** [comment]
What's the status on this issue?

**Comment by haggi** [comment]
Working on it. It will be fixed in one of the next PR. I found some strange things I implemented, now I'm cleaning up :)

**Comment by haggi** [comment]
Fixed in PR #51.
