### ISSUE TITLE
The last rendered tile remains highlighted after rendering has finished

### ISSUE THREAD

**Issue by dictoon** [appleseedhq/appleseed-maya#31]
![image](https://cloud.githubusercontent.com/assets/321290/12867182/060dae0c-cce7-11e5-86fa-59ed19d5bf2a.png)

**Comment by dictoon** [comment]
Temporarily fixed by no longer displaying the rectangles. Technically this was achieved by setting the `doNotClearBackground` argument of `MRenderView::startRender()` to false (i.e. do clear background).

**Comment by haggi** [comment]
The solution is not really useful because we often want to see the background during rendering.

**Comment by haggi** [comment]
But I found another solution thanks to Autodesk Area support via MRenderView::setDrawTileBoundary(false).

**Comment by dictoon** [comment]
Did the new solution got merged into master yet?

**Comment by haggi** [comment]
Ah, sorry. No, not yet. I fixed it in my next PR.

**Comment by dictoon** [comment]
Let's close it when the fix is in :)

**Comment by haggi** [comment]
Fixed in PR #52.
