### ISSUE TITLE
Appleseed materials cannot be assigned

### ISSUE THREAD

**Issue by est77** [appleseedhq/appleseed-maya#41]
Seems related to removing the standard Maya material classification.
Probably we miss some hypershade callbacks.

**Comment by luisbarrancos** [comment]
@est77 wait, let me review this, will ping you in a bit, because i remember applying custom materials, after we changed that metadata. Materials and custom nodes (Voronoi).

**Comment by luisbarrancos** [comment]
@est77 i can assign here, but i had to set APPLESEED_SEARCHPATH to my OSL_SHADERS, which points to the sandbox/shaders/appleseed and sandbox/shaders/maya location.
Feel free to close.

**Comment by luisbarrancos** [comment]
@est77 it requires *shader/surface* classification for shader types, so it seems we cannot have it only in the Appleseed menu (?). If i add *shader/surface* i can assign it.

**Comment by luisbarrancos** [comment]
Fix in PR.

**Comment by luisbarrancos** [comment]
Fixed in https://github.com/appleseedhq/appleseed/pull/1410
