### ISSUE TITLE
Maya (string) object name

### ISSUE THREAD

**Issue by luisbarrancos** [appleseedhq/appleseed-maya#43]
For the N-switch nodes we need the Maya object name since we need to compare this against the shading node string. This means the equivalent of a 
```
RiAttribute "user" "string" "objectname" ["foobar"]
```
Which would be queried with something like
```
int status = getattribute("user:objectname", nodename);
```

**Comment by luisbarrancos** [comment]
On the other side, N-switch nodes are going to need a custom exporter.
@est77 what approach to follow here?

![screenshot_2017-05-01_11-34-29](https://cloud.githubusercontent.com/assets/387352/25571454/5cdf8682-2e62-11e7-92d5-56149f908a9a.png)

**Comment by est77** [comment]
Done in appleseed, here: 2f2f0801def6a93414d849250602ce4e86361d99
