### ISSUE TITLE
Maya (string) render space from general CMS as user option

### ISSUE THREAD

**Issue by luisbarrancos** [appleseedhq/appleseed-maya#44]
There are plenty of nodes that have render space dependent operations. 
We need the equivalent of a 
```
RiOption "user" "renderspace" ["Rec.2020"]
```
to be queried via a
```
int status = getattribute("user:renderspace", renderspace);
```
This would actually be needed as well for AS in general, it's not exclusively a Maya feature.

**Comment by est77** [comment]
Done in appleseed, here: 2b2ff747cb233c2309d933d160adc878c3ce175e
Will be included when the PR is merged.
