### ISSUE TITLE
Update README.md to keep consistency with main project

### ISSUE THREAD

**Issue by luisbarrancos** [appleseedhq/appleseed-maya#62]

**Comment by dictoon** [comment]
Closed because it's done, but not yet pushed?

**Comment by luisbarrancos** [comment]
Well, the docs have the support status for the maya nodes. The idea was to have the main mayaseed docs here, or at least a placeholder for the installation and support status pages of the docs, otherwise we need to keep updating both.

**Comment by dictoon** [comment]
I'm not sure we're talking about the same thing.

The "homepage" of appleseed-maya (https://github.com/appleseedhq/appleseed-maya, as specified by README.md) and of all the plugins (appleseed-max, blenderseed, maybe even gafferseed) should look like the one of appleseed itself. With a different render, maybe a slightly different layout, but there should be some consistency between the various components of the "appleseed ecosystem" on GitHub.

So I would suggest moving installation instructions, planned features and supported nodes to specific sections of the docs on RTD.

This is what this ticket is about.

**Comment by luisbarrancos** [comment]
Ok, we were talking about different things. I had added already the installation instructions, supported nodes, and so on, to the docs, and wanted to avoid having them as well here (i.e: the support nodes matrix), but having consistency with i.e: maxseed, etc, sure.

**Comment by dictoon** [comment]
Done.
