### ISSUE TITLE
Test "docs" branch, main trigger for RTD builds

### ISSUE THREAD

**Issue by luisbarrancos** [appleseedhq/appleseed-maya#64]
Otherwise the *latest* branch is always built upon a **push** (default) or **PR** event.
A parallel *docs* branch could be used to trigger builds, and synchronized with master on major milestones, i.e, RC, beta, release versions.
This until someone figures out how on Earth you can trigger a RTD build on any specific/filtered criteria.

**Comment by dictoon** [comment]
I'm wondering, is it really a problem to rebuild docs for every commit on master?

**Comment by luisbarrancos** [comment]
@dictoon not really, i'm ok with that. I'm not sure the previous builds of the docs are hosted, probably not. Feel free to close this if you agree.

**Comment by dictoon** [comment]
Ok, let's worry about this if/when it ever becomes a problem! Closing this issue for now.
