### ISSUE TITLE
Add a global scene scale setting

### ISSUE THREAD

**Issue by est77** [appleseedhq/appleseed-maya#72]

**Comment by luisbarrancos** [comment]
@est77 the default Maya scene units? That would be great. I could implement the transformu node.

**Comment by est77** [comment]
It's a global scene scale factor. We have it in Max. It's useful to convert your scene units, if for example your scene is modelled in centimeters and you want to export the project in meters.

Done in ff351a2af0387ae6408f62defccff9bfcc8516cd
